Repository epics-modules/mrfioc2, pull requests merged in 2023-10, with the labels that each got.

#81 fix: Special separator ':' changed to makro $(s=:).
  evgMrmApp/Db/evgDbus.db
  evgMrmApp/Db/evgSoftSeq.template
  evgMrmApp/Db/evgTrigEvt.db
  evgMrmApp/Db/evm-fct.template
  evgMrmApp/Db/seq-repeater.db
  evrApp/Db/evrNtp.db
  evrApp/Db/evralias.db
  evrApp/Db/evrbase.db
  evrApp/Db/evrcml.db
  evrApp/Db/evrcmlextra.db
  evrApp/Db/evrevent-cycle.db
  evrApp/Db/evrin.db
  evrApp/Db/evrpulser.db
  evrApp/Db/evrscale.db
  evrApp/Db/evrsoftgate.db
  evrFRIBApp/Db/fribevrout.db
  evrMrmApp/Db/evrSoftSeq.template
  evrMrmApp/Db/mrmevrbase.template
  evrMrmApp/Db/mrmevrbufrx.db
  evrMrmApp/Db/mrmevrout.db
  evrMrmApp/Db/sequencedemo.db
  mrmShared/Db/databuftx.db
  mrmShared/Db/databuftxCtrl.db
  mrmShared/Db/mrmSoftSeq.template
  mrmShared/Db/sfp.db
Labels: fix

#84 fix: $(SYS) and {$(D)} addressed with PP
  evgMrmApp/Db/evgInput.db
  evgMrmApp/Db/evgMxc.db
  evgMrmApp/Db/evgSoftSeq.template
  evrMrmApp/Db/mrmevrtsbuf.db
Labels: fix

#85 feat: evm-mtca-300 - naming agnostic substitutions.
  .github/CODEOWNERS
  evgMrmApp/Db/Makefile
  evgMrmApp/Db/evm-mtca-300-evr.substitutions
  evgMrmApp/Db/evm-mtca-300.substitutions
Labels: feature, fix

#86 feat: Naming agnostic EVR 300 added.
  evrMrmApp/Db/Makefile
  evrMrmApp/Db/evr-300.substitutions
  evrMrmApp/Db/evrSoftSeq.template
Labels: feature, fix

#88 feat: Univ and RB outputs + TB inputs added.
  evrMrmApp/src/drvemSetup.cpp
Labels: feature

#90 feat: More outputs up to UNIV15 + inputs up to FPUV19.
  evrMrmApp/Db/evr-pcie-300dc.substitutions
Labels: feature

#91 feat: Univ Sources added up to 15 for EVG.
  evgMrmApp/Db/evgTrigEvt.db
Labels: feature

#93 fix: Better handling of the clocks for EVR widths and delays.
  evrMrmApp/src/drvemPulser.cpp
Labels: fix

#60 Add prescaler polarity selection
  evrApp/Db/evrscale.db
  evrMrmApp/src/drvem.cpp
  evrMrmApp/src/drvem.h
  evrMrmApp/src/evrRegMap.h
Labels: feature

#58 Fix RFDIV macro
  evgMrmApp/Db/cpci-evg-300.substitutions
  evgMrmApp/Db/mtca-evm-300.substitutions
  evgMrmApp/Db/vme-evg230-nsls2.substitutions
  evgMrmApp/Db/vme-evg230.substitutions
Labels: fix

#62 Add pulser software set/reset
  evrApp/Db/evrpulser.db
  evrApp/src/evr.cpp
  evrApp/src/evr/pulser.h
  evrFRIBApp/src/evr_frib.h
  evrMrmApp/src/drvemPulser.cpp
  evrMrmApp/src/drvemPulser.h
Labels: feature

#59 Display softseq errors on the GUI
  mrmShared/src/mrmSeq.cpp
Labels: feature

#101 fix: TX, RX power and Link speed alarms extended to support faster SFP modules.
  mrmShared/Db/sfp.db
Labels: fix

#95 feat: MTCA EVR FPUNIV, backplane CLKA/B handling added.
  evrMrmApp/Db/evr-mtca-300.substitutions
Labels: feature, fix

#94 fix: TCLKA and TCLKB and EVRU/EVRD clocks.
  evrMrmApp/src/drvem.cpp
Labels: fix
