Repository epics-modules/mrfioc2, pull requests merged in 2024-04, with the labels that each got.

#143 fix: Use softclock if the registry empty for EVRU/D.
  evrMrmApp/src/drvem.cpp
Labels: enhancement, fix

#144 add evgMrmShared depends also on evrApp because of internval EVRs
  Makefile
Labels: fix, build

#146 fix: version fetched from only digital git tags
  mrfCommon/src/genVersionHeader.pl
Labels: enhancement, build
