Repository epics-modules/mrfioc2, pull requests merged in 2024-09, with the labels that each got.

#169 Adding more selection options in evm db files
  evgMrmApp/Db/evgDbus.db
  evgMrmApp/Db/evgMrm.db
  evgMrmApp/Db/evgTrigEvt.db
  evgMrmApp/src/evgInit.cpp
Labels: feature

#177 Add the EVM frac Synth reset function
  evgMrmApp/Db/evgMrm.db
  evgMrmApp/src/evg.cpp
  evgMrmApp/src/evgMrm.cpp
  evgMrmApp/src/evgMrm.h
Labels: feature

#179 feat: Fine delay for rear transition board
  evrMrmApp/Db/Makefile
  evrMrmApp/Db/evr-mtca-300u.uv.substitutions
  evrMrmApp/Db/evr-vme-300.substitutions
  evrMrmApp/Db/mrmevrdlymodule.template
  evrMrmApp/Db/mrmevroutdly.db
  evrMrmApp/src/drvem.h
  evrMrmApp/src/drvemOutput.cpp
  evrMrmApp/src/drvemOutput.h
  evrMrmApp/src/evrRegMap.h
Labels: enhancement, feature

#162 CML/GTX supports for EVR-VME300
  evrMrmApp/src/drvemCML.cpp
Labels: feature

#181 db file update and bug fix
  evgMrmApp/Db/evgDbus.db
  evgMrmApp/Db/evgInput.db
  evgMrmApp/Db/evm-mtca-300.uv.substitutions
  evgMrmApp/Db/evm-vme-300.substitutions
  evrMrmApp/Db/evr-vme-300.substitutions
Labels: enhancement, fix

#182 feat: MTCA EVM expanded with the Backplane and Transition Board outputs
  evgMrmApp/Db/evm-mtca-300.uv.substitutions
  evgMrmApp/src/evgInit.cpp
  evgMrmApp/src/evgInput.h
  evgMrmApp/src/evgMrm.cpp
  evgMrmApp/src/evgMrm.h
  evgMrmApp/src/evgOutput.cpp
  evgMrmApp/src/evgOutput.h
  evgMrmApp/src/evgRegMap.h
Labels: feature

#184 feat: Evg reg report map update.
  evgMrmApp/src/evgInit.cpp
Labels: enhancement
