Repository epics-modules/mrfioc2, pull requests merged in 2024-11, with the labels that each got.

#194 add the 3rd option of sequencer source, install the template
  evgMrmApp/Db/Makefile
  evgMrmApp/Db/evgSoftSeq.template
Labels: feature

#196 feat: kmod support for Centos Stream 9
  .github/workflows/ci-scripts-build.yml
  .github/workflows/linux-build-latest.yml
  .github/workflows/linux-build.yml
  mrmShared/linux/uio_mrf.c
Labels: enhancement

#197 adding more db and template files to the install directory
  evrMrmApp/Db/Makefile
  mrmShared/Db/Makefile
Labels: enhancement

#198 Improve deb file to use generic udev rules
  mrmShared/linux/debian/mrf-dkms.udev
  mrmShared/linux/debian/rules
Labels: fix

#199 bug fix: remove macro s in Seq Trigger Source Selection OUT link
  evgMrmApp/Db/evgSoftSeq.template
Labels: fix
