Repository epics-modules/mrfioc2, pull requests merged in 2024-01, with the labels that each got.

#111 feat: lspci update for MTCA devices.
  documentation/lspci/mtca-evm-300.txt
  documentation/lspci/mtca-evr-300u.txt
  documentation/lspci/pcie-evr-300dc.txt
Labels: documentation

#110 feat: Better handling of GTX within formFactor_mTCA.
  evrMrmApp/Makefile
  evrMrmApp/src/drvem.cpp
  evrMrmApp/src/drvemSetup.cpp
Labels: enhancement

#61 Pulser trigger with DBus bits and prescalers
  evrApp/Db/evrpulser.db
  evrApp/src/evr.cpp
  evrApp/src/evr/pulser.h
  evrFRIBApp/src/evr_frib.h
  evrMrmApp/src/drvemPulser.cpp
  evrMrmApp/src/drvemPulser.h
  evrMrmApp/src/evrRegMap.h
Labels: feature

#114 docs: Update of the release versioning.
  configure/CONFIG_MRFIOC2_VERSION
  documentation/Doxyfile
  documentation/mainpage.h
Labels: documentation

#116 feat: Macros controlling the EVRU/D irqpoller.
  evgMrmApp/src/evgInit.cpp
Labels: enhancement

#117 fix: Correct the setFrequency command
  evgMrmApp/src/evgMxc.cpp
Labels: fix
